# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NowlyTree < Formula
  desc "Nowly Lab's Homebrew distribution of dep-tree."
  homepage "https://github.com/nowly-lab/dep-tree"
  version "0.23.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.20/nowly-tree_darwin_amd64.tar.gz"
      sha256 "c3b2f62cb657acf272e71ca5018910fcbfad8e6b58404d778d3be150f6d8bc80"

      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.20/nowly-tree_darwin_arm64.tar.gz"
      sha256 "004347e340e9df6770ba90f4433defb2f19d7a4b9f8d59ed40421bfa3743abcd"

      def install
        bin.install "nowly-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.20/nowly-tree_linux_amd64.tar.gz"
      sha256 "dfa7f87539c3b3208cfb37f5310fe913566f7c5965b3ed425d6a05685ac8feac"
      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.20/nowly-tree_linux_arm64.tar.gz"
      sha256 "4aaf7fabb2a503ace93531a60c6baa397c34f619ed0cc08f946e53368aed7e9c"
      def install
        bin.install "nowly-tree"
      end
    end
  end

  test do
    system "#{bin}/nowly-tree", "--version"
  end
end
